version: '3.8'

services:
  web-scanner:
    build: .
    container_name: web-security-scanner
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - scanner-network

networks:
  scanner-network:
    driver: bridge
